//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Replica.Domain.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Replica.Domain.Localization.Lang.Errors", typeof(Lang_Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з такою email адресою вже існує.
        /// </summary>
        internal static string Authentication_DuplicateEmail {
            get {
                return ResourceManager.GetString("Authentication.DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркер доступу пошкоджено, або згенеровано стороннім сервісом.
        /// </summary>
        internal static string Authentication_InvalidToken {
            get {
                return ResourceManager.GetString("Authentication.InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Термін дії маркера оновлення минув.
        /// </summary>
        internal static string Authentication_RefreshTokenExpired {
            get {
                return ResourceManager.GetString("Authentication.RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль з таким ідентефікатором відсутня.
        /// </summary>
        internal static string Role_NotFound {
            get {
                return ResourceManager.GetString("Role.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такий тег вже існує.
        /// </summary>
        internal static string Tag_AlreadyExists {
            get {
                return ResourceManager.GetString("Tag.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тег з таким ідентифікатором відсутній.
        /// </summary>
        internal static string Tag_NotFound {
            get {
                return ResourceManager.GetString("Tag.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даний користувач заблокований.
        /// </summary>
        internal static string User_Blocked {
            get {
                return ResourceManager.GetString("User.Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з таким ідентифікатором відсутній.
        /// </summary>
        internal static string User_NotFound {
            get {
                return ResourceManager.GetString("User.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний пароль користувача.
        /// </summary>
        internal static string User_WrongPassword {
            get {
                return ResourceManager.GetString("User.WrongPassword", resourceCulture);
            }
        }
    }
}
